# Generated by Django 2.0.4 on 2018-04-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180420_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Course'),
        ),
    ]
